In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
%matplotlib inline

In [3]:
housing_df = pd.read_csv("./data/kc_house_data_original.csv")

In [4]:
housing_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21613 entries, 0 to 21612
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   id             21613 non-null  int64  
 1   date           21613 non-null  object 
 2   price          21613 non-null  float64
 3   bedrooms       21613 non-null  int64  
 4   bathrooms      21613 non-null  float64
 5   sqft_living    21613 non-null  int64  
 6   sqft_lot       21613 non-null  int64  
 7   floors         21613 non-null  float64
 8   waterfront     21613 non-null  int64  
 9   view           21613 non-null  int64  
 10  condition      21613 non-null  int64  
 11  grade          21613 non-null  int64  
 12  sqft_above     21613 non-null  int64  
 13  sqft_basement  21613 non-null  int64  
 14  yr_built       21613 non-null  int64  
 15  yr_renovated   21613 non-null  int64  
 16  zipcode        21613 non-null  int64  
 17  lat            21613 non-null  float64
 18  long  

In [5]:
housing_df.head()

id             date     price  bedrooms  bathrooms  sqft_living  \
0  7129300520  20141013T000000  221900.0         3       1.00         1180   
1  6414100192  20141209T000000  538000.0         3       2.25         2570   
2  5631500400  20150225T000000  180000.0         2       1.00          770   
3  2487200875  20141209T000000  604000.0         4       3.00         1960   
4  1954400510  20150218T000000  510000.0         3       2.00         1680   

   sqft_lot  floors  waterfront  view  ...  grade  sqft_above  sqft_basement  \
0      5650     1.0           0     0  ...      7        1180              0   
1      7242     2.0           0     0  ...      7        2170            400   
2     10000     1.0           0     0  ...      6         770              0   
3      5000     1.0           0     0  ...      7        1050            910   
4      8080     1.0           0     0  ...      8        1680              0   

   yr_built  yr_renovated  zipcode      lat     long  sqft_living15  \
0      1955             0    98178  47.5112 -122.257           1340   
1      1951          1991    98125  47.7210 -122.319           1690   
2      1933             0    98028  47.7379 -122.233           2720   
3      1965             0    98136  47.5208 -122.393           1360   
4      1987             0    98074  47.6168 -122.045           1800   

   sqft_lot15  
0        5650  
1        7639  
2        8062  
3        5000  
4        7503  

[5 rows x 21 columns]

In [6]:
print(int(True), int(False))

1 0


In [7]:
housing_df['price_gt_1M'] = housing_df['price'].map(lambda x: int(x >= 1000000)) 

In [8]:
housing_df = housing_df.iloc[:, 2:]
housing_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21613 entries, 0 to 21612
Data columns (total 20 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   price          21613 non-null  float64
 1   bedrooms       21613 non-null  int64  
 2   bathrooms      21613 non-null  float64
 3   sqft_living    21613 non-null  int64  
 4   sqft_lot       21613 non-null  int64  
 5   floors         21613 non-null  float64
 6   waterfront     21613 non-null  int64  
 7   view           21613 non-null  int64  
 8   condition      21613 non-null  int64  
 9   grade          21613 non-null  int64  
 10  sqft_above     21613 non-null  int64  
 11  sqft_basement  21613 non-null  int64  
 12  yr_built       21613 non-null  int64  
 13  yr_renovated   21613 non-null  int64  
 14  zipcode        21613 non-null  int64  
 15  lat            21613 non-null  float64
 16  long           21613 non-null  float64
 17  sqft_living15  21613 non-null  int64  
 18  sqft_l

In [9]:
newcols_class = [_ for _ in range(1, 20)]
newcols_class

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [10]:
newcols_regression = [_ for _ in range(1, 18)]
newcols_regression.extend([0])
newcols_regression

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 0]

In [11]:
housing_class_df = housing_df.iloc[:, newcols_class]
housing_class_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21613 entries, 0 to 21612
Data columns (total 19 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   bedrooms       21613 non-null  int64  
 1   bathrooms      21613 non-null  float64
 2   sqft_living    21613 non-null  int64  
 3   sqft_lot       21613 non-null  int64  
 4   floors         21613 non-null  float64
 5   waterfront     21613 non-null  int64  
 6   view           21613 non-null  int64  
 7   condition      21613 non-null  int64  
 8   grade          21613 non-null  int64  
 9   sqft_above     21613 non-null  int64  
 10  sqft_basement  21613 non-null  int64  
 11  yr_built       21613 non-null  int64  
 12  yr_renovated   21613 non-null  int64  
 13  zipcode        21613 non-null  int64  
 14  lat            21613 non-null  float64
 15  long           21613 non-null  float64
 16  sqft_living15  21613 non-null  int64  
 17  sqft_lot15     21613 non-null  int64  
 18  price_

In [12]:
housing_regression_df = housing_df.iloc[:, newcols_regression]
housing_regression_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21613 entries, 0 to 21612
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   bedrooms       21613 non-null  int64  
 1   bathrooms      21613 non-null  float64
 2   sqft_living    21613 non-null  int64  
 3   sqft_lot       21613 non-null  int64  
 4   floors         21613 non-null  float64
 5   waterfront     21613 non-null  int64  
 6   view           21613 non-null  int64  
 7   condition      21613 non-null  int64  
 8   grade          21613 non-null  int64  
 9   sqft_above     21613 non-null  int64  
 10  sqft_basement  21613 non-null  int64  
 11  yr_built       21613 non-null  int64  
 12  yr_renovated   21613 non-null  int64  
 13  zipcode        21613 non-null  int64  
 14  lat            21613 non-null  float64
 15  long           21613 non-null  float64
 16  sqft_living15  21613 non-null  int64  
 17  price          21613 non-null  float64
dtypes: flo

In [13]:
housing_class_df.to_csv("./data/kc_house_data_classification.csv", index=False)

In [14]:
housing_regression_df.to_csv("./data/kc_house_data_regression.csv", index=False)

In [15]:
# Task 4: Categorize Feature Types

categorical_features = ['waterfront', 'view', 'condition', 'grade', 'zipcode']
numerical_features = [col for col in housing_df.columns if col not in categorical_features + ['price_gt_1M']]

In [16]:
# Task 4: Train-Test split
from sklearn.model_selection import train_test_split

X = housing_df.drop(columns=['price_gt_1M'])
y = housing_df['price_gt_1M']

#  train_test_split function
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=73)

print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)


X_train shape: (17290, 19)
X_test shape: (4323, 19)
y_train shape: (17290,)
y_test shape: (4323,)


In [17]:
# Define logistic regression model

# Model 0: The null model
from sklearn.dummy import DummyClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

# Null model
null_model = DummyClassifier(strategy='most_frequent')
null_model.fit(X_train, y_train)

# Predictions
y_train_pred = null_model.predict(X_train)
y_test_pred = null_model.predict(X_test)

# Accuracy scores
print(f'Null model training accuracy: {accuracy_score(y_train, y_train_pred):.3f}')
print(f'Null model test accuracy: {accuracy_score(y_test, y_test_pred):.3f}')

# Confusion matrices
print('Training Confusion Matrix:\n', confusion_matrix(y_train, y_train_pred))
print('Test Confusion Matrix:\n', confusion_matrix(y_test, y_test_pred))

Null model training accuracy: 0.933
Null model test accuracy: 0.924
Training Confusion Matrix:
 [[16127     0]
 [ 1163     0]]
Test Confusion Matrix:
 [[3994    0]
 [ 329    0]]


In [18]:
#Model 1: Ridge Regression with C=1.0

from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer

# Preprocessing pipeline
preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), numerical_features),
        ('cat', OneHotEncoder(), categorical_features)
    ])

# Ridge regression model
ridge_model = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', LogisticRegression(C=1.0, penalty='l2', solver='saga', max_iter=2000))
])

ridge_model.fit(X_train, y_train)

# Predictions
y_train_pred = ridge_model.predict(X_train)
y_test_pred = ridge_model.predict(X_test)

# Accuracy scores
print(f'Ridge Regression training accuracy: {accuracy_score(y_train, y_train_pred):.3f}')
print(f'Ridge Regression test accuracy: {accuracy_score(y_test, y_test_pred):.3f}')

# Confusion matrices
print('Training Confusion Matrix:\n', confusion_matrix(y_train, y_train_pred))
print('Test Confusion Matrix:\n', confusion_matrix(y_test, y_test_pred))

Ridge Regression training accuracy: 0.998
Ridge Regression test accuracy: 0.995
Training Confusion Matrix:
 [[16115    12]
 [   31  1132]]
Test Confusion Matrix:
 [[3992    2]
 [  21  308]]


In [19]:
#Model 2: Lasso Regression with C=1.0

from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.model_selection import train_test_split

# Preprocessing pipeline
preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), numerical_features),
        ('cat', OneHotEncoder(), categorical_features)
    ])

# Lasso regression model
lasso_model = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', LogisticRegression(C=1.0, penalty='l1', solver='saga', max_iter=5000))
])

lasso_model.fit(X_train, y_train)

# Predictions
y_train_pred = lasso_model.predict(X_train)
y_test_pred = lasso_model.predict(X_test)

# Accuracy scores
print(f'Lasso Regression training accuracy: {accuracy_score(y_train, y_train_pred):.3f}')
print(f'Lasso Regression test accuracy: {accuracy_score(y_test, y_test_pred):.3f}')

# Confusion matrices
print('Training Confusion Matrix:\n', confusion_matrix(y_train, y_train_pred))
print('Test Confusion Matrix:\n', confusion_matrix(y_test, y_test_pred))

Lasso Regression training accuracy: 0.999
Lasso Regression test accuracy: 0.997
Training Confusion Matrix:
 [[16124     3]
 [   22  1141]]
Test Confusion Matrix:
 [[3993    1]
 [  13  316]]


In [20]:
#Model 3: Lasso Regression with C=0.01

# Lasso regression model with C=0.01

lasso_model_001 = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', LogisticRegression(C=0.01, penalty='l1', solver='saga', max_iter=5000))
])


lasso_model_001.fit(X_train, y_train)

# Predictions
y_train_pred = lasso_model_001.predict(X_train)
y_test_pred = lasso_model_001.predict(X_test)

# Accuracy scores
print(f'Lasso Regression (C=0.01) training accuracy: {accuracy_score(y_train, y_train_pred):.3f}')
print(f'Lasso Regression (C=0.01) test accuracy: {accuracy_score(y_test, y_test_pred):.3f}')

# Confusion matrices
print('Training Confusion Matrix:\n', confusion_matrix(y_train, y_train_pred))
print('Test Confusion Matrix:\n', confusion_matrix(y_test, y_test_pred))

Lasso Regression (C=0.01) training accuracy: 0.991
Lasso Regression (C=0.01) test accuracy: 0.989
Training Confusion Matrix:
 [[16127     0]
 [  158  1005]]
Test Confusion Matrix:
 [[3994    0]
 [  47  282]]


In [ ]:
#Model 4: Lasso Regression with Optimal C

from sklearn.linear_model import LogisticRegressionCV

# Lasso regression with cross-validated optimal C
lasso_cv_model = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', LogisticRegressionCV(Cs=10, cv=5, penalty='l1', solver='saga', max_iter=5000))
])

lasso_cv_model.fit(X_train, y_train)

# Optimal C
optimal_C = lasso_cv_model.named_steps['classifier'].C_[0]
print(f'Optimal C value: {optimal_C}')

# Predictions
y_train_pred = lasso_cv_model.predict(X_train)
y_test_pred = lasso_cv_model.predict(X_test)

# Accuracy scores
print(f'Lasso Regression CV training accuracy: {accuracy_score(y_train, y_train_pred):.3f}')
print(f'Lasso Regression CV test accuracy: {accuracy_score(y_test, y_test_pred):.3f}')

# Confusion matrices
print('Training Confusion Matrix:\n', confusion_matrix(y_train, y_train_pred))
print('Test Confusion Matrix:\n', confusion_matrix(y_test, y_test_pred))

In [ ]:
#Task 5 
from sklearn.tree import DecisionTreeClassifier
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.metrics import accuracy_score, confusion_matrix

# Preprocessing pipeline
preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), numerical_features),
        ('cat', OneHotEncoder(), categorical_features)
    ])

# Decision tree model
tree_model = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', DecisionTreeClassifier(random_state=73))
])

tree_model.fit(X_train, y_train)

# Predictions
y_train_pred = tree_model.predict(X_train)
y_test_pred = tree_model.predict(X_test)

# Accuracy scores
print(f'Decision Tree training accuracy: {accuracy_score(y_train, y_train_pred):.3f}')
print(f'Decision Tree test accuracy: {accuracy_score(y_test, y_test_pred):.3f}')

# Confusion matrices
print('Training Confusion Matrix:\n', confusion_matrix(y_train, y_train_pred))
print('Test Confusion Matrix:\n', confusion_matrix(y_test, y_test_pred))


In [ ]:
# compute the accuracy score, create a confusion matrix, and discuss the performance relative to your logistic regression models

# Compute accuracy scores for both training and test sets
train_accuracy = accuracy_score(y_train, y_train_pred)
test_accuracy = accuracy_score(y_test, y_test_pred)

# Print accuracy scores
print(f'Decision Tree training accuracy: {train_accuracy:.3f}')
print(f'Decision Tree test accuracy: {test_accuracy:.3f}')

# Create confusion matrices
train_conf_matrix = confusion_matrix(y_train, y_train_pred)
test_conf_matrix = confusion_matrix(y_test, y_test_pred)

# Print confusion matrices
print('Training Confusion Matrix:\n', train_conf_matrix)
print('Test Confusion Matrix:\n', test_conf_matrix)

*discussion-
When comparing the decision tree model to the logistic regression models (both Ridge and Lasso), consider the following:

Accuracy Scores - Higher accuracy on the training set often indicates that the decision tree may be overfitting. Overfitting is when the model performs well on training data but poorly on test data.
Confusion Matrices: These provide more detailed insights into the types of errors being made, which is crucial for understanding model performance beyond just accuracy.
Decision trees are flexible models that can capture complex patterns in the data but are also prone to overfitting. This is in contrast to logistic regression models, which are less flexible and thus less likely to overfit, especially with regularization (Ridge and Lasso).


In [ ]:
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.metrics import accuracy_score, confusion_matrix
import matplotlib.pyplot as plt

# Assuming 'decision_tree' is previously defined and fitted
decision_tree = tree_model

# Get feature names for the categorical variables after one-hot encoding
onehot_feature_names = decision_tree.named_steps['preprocessor'].named_transformers_['cat'].get_feature_names_out(categorical_features)

# Combine numerical feature names with the expanded categorical feature names
all_feature_names = numerical_features + onehot_feature_names.tolist()

# Plot the tree
plt.figure(figsize=(20,10))
plot_tree(decision_tree.named_steps['classifier'], filled=True, feature_names=all_feature_names, class_names=['<=1M', '>1M'])
plt.show()



*We don't need to create a coefficient plot for decision trees because decision trees do not have coefficients like linear models (e.g., logistic regression). In logistic regression, the coefficients represent the contribution of each feature to the predicted outcome, and visualizing them helps understand which features are more influential in the model's decision-making process.

However, decision trees make splits in the feature space based on threshold values, rather than coefficients. Therefore, visualizing a decision tree typically involves plotting the tree structure itself to understand how the features are used to make decisions at each node. This visualization provides insights into the decision-making process of the tree model, rather than coefficients representing feature importance.

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.metrics import accuracy_score, confusion_matrix


# Define and fit the Lasso model
preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), numerical_features),
        ('cat', OneHotEncoder(), categorical_features)
    ])

lasso_model = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', LogisticRegression(C=1.0, penalty='l1', solver='saga', max_iter=5000))
])

# Assuming 'X_train' and 'y_train' are already defined
lasso_model.fit(X_train, y_train)

# Predictions
lasso_predictions = lasso_model.predict(X_test)

# Convert lasso_predictions to a pandas Series
lasso_predictions = pd.Series(lasso_predictions, index=X_test.index)

# Load the original test data
test_data = pd.read_csv("./data/kc_house_data_classification.csv")

# Load the regression dataset to get the actual prices
regression_data = pd.read_csv("./data/kc_house_data_regression.csv")

# Extract the test indices used in the train-test split
test_indices = X_test.index

# Filter the test_data and regression_data using the test indices
test_data = test_data.loc[test_indices]
regression_data = regression_data.loc[test_indices]

# Join the regression dataset with the test data based on the index
merged_data = test_data.join(regression_data.set_index(test_data.index), rsuffix='_regression')

# Ensure the indices are properly aligned
y_test = y_test.reset_index(drop=True)
lasso_predictions = lasso_predictions.reset_index(drop=True)
merged_data = merged_data.reset_index(drop=True)

# Extract the actual prices for the rows where the predictions were incorrect
incorrect_predictions = merged_data.loc[lasso_predictions != y_test]
incorrect_prices = incorrect_predictions['price']

# Plot a histogram of the actual prices for the incorrect predictions
plt.hist(incorrect_prices, bins=20, color='skyblue', edgecolor='black')
plt.xlabel('Actual Price')
plt.ylabel('Frequency')
plt.title('Histogram of Actual Prices for Incorrect Predictions')
plt.show()


In [ ]:
# Hacker Extra
# Part 1 - Histogram-based Gradient Boosting Classifier

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.ensemble import HistGradientBoostingClassifier
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.model_selection import train_test_split

# Load the dataset
classification_df = pd.read_csv('./data/kc_house_data_classification.csv')

# Define features and target
categorical_features = ['waterfront', 'view', 'condition', 'grade', 'zipcode']
numeric_features = [col for col in classification_df.columns if col not in categorical_features + ['price_gt_1M']]
X = classification_df.drop(columns='price_gt_1M')
y = classification_df['price_gt_1M']

# Split data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=73)

# Preprocessing
preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), numeric_features),
        ('cat', OneHotEncoder(sparse_output=False), categorical_features)
    ])

# Histogram-based Gradient Boosting model pipeline
hgb_pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', HistGradientBoostingClassifier(random_state=73))
])

# Fit the model
hgb_pipeline.fit(X_train, y_train)

# Predictions
y_train_pred = hgb_pipeline.predict(X_train)
y_test_pred = hgb_pipeline.predict(X_test)

# Accuracy scores
print(f'Histogram-based Gradient Boosting training accuracy: {accuracy_score(y_train, y_train_pred):.3f}')
print(f'Histogram-based Gradient Boosting test accuracy: {accuracy_score(y_test, y_test_pred):.3f}')

# Confusion matrices
print('Training Confusion Matrix:\n', confusion_matrix(y_train, y_train_pred))
print('Test Confusion Matrix:\n', confusion_matrix(y_test, y_test_pred))

# Plot confusion matrix for test set
plt.figure(figsize=(8, 8))
plt.imshow(confusion_matrix(y_test, y_test_pred), interpolation='nearest', cmap=plt.cm.Blues)
plt.title('Confusion Matrix')
plt.colorbar()
tick_marks = [0, 1]
plt.xticks(tick_marks, ['<=1M', '>1M'], rotation=0)
plt.yticks(tick_marks, ['<=1M', '>1M'])
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.grid(False)
plt.show()


In [ ]:
#Part-2 Lasso Regression for Price Prediction

from sklearn.linear_model import LassoCV

# Load the dataset
housing_df_reg = pd.read_csv('./data/kc_house_data_regression.csv')

# Define features and target
X = housing_df_reg.drop('price', axis=1)
y = housing_df_reg['price']

# Preprocessing and LassoCV
preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), X.select_dtypes(include=['int64', 'float64']).columns),
        ('cat', OneHotEncoder(), X.select_dtypes(include=['object']).columns)
    ]
)

lasso_cv_model = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('regressor', LassoCV(cv=5))
])

lasso_cv_model.fit(X, y)

# Optimal alpha
optimal_alpha = lasso_cv_model.named_steps['regressor'].alpha_
print(f'Optimal alpha value: {optimal_alpha}')

# Predictions
y_pred = lasso_cv_model.predict(X)

# Performance metrics
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(y, y_pred)
print(f'Mean Squared Error: {mse}')